# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://joseph-montgomery.com
title: J.J.
email: joseph.j.montgomery@gmail.com
author: J.J. Montgomery
description: > # "Write an awesome description for your new site here. 
  My name is J.J. Montgomery. I'm a software developer in the Seattle area.
copyright: 'Copyright &copy; 2025 Joseph Montgomery. All Rights Reserved.'
credits: 'Credits: Theme by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/jmonty42
  - title: linkedin
    url: https://www.linkedin.com/in/josephjmontgomery
